name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"           # speeds up installs using your requirements.txt
          cache-dependency-path: "requirements.txt"

      - name: Install deps
        run: make install

      - name: Run tests (pytest + coverage)
        run: make test

      - name: Upload coverage artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-files
          path: |
            .coverage
            .pytest_cache
